In [1]:
import numpy as np
import pandas as pd

Data Frame

In [6]:
df = pd.DataFrame(np.random.randn(5,4),columns=['W','X','Y','Z'])

In [7]:
df

          W         X         Y         Z
0 -1.128595 -1.737227 -0.242487  0.851138
1 -1.702400 -0.149407 -2.226871 -1.306226
2 -0.942597  1.718965 -1.069582  1.176526
3 -3.164213 -0.153966 -0.322251  0.638019
4  0.267006  0.528366 -0.845436 -1.257159

In [8]:
df['W']

0   -1.128595
1   -1.702400
2   -0.942597
3   -3.164213
4    0.267006
Name: W, dtype: float64

In [9]:
df.W

0   -1.128595
1   -1.702400
2   -0.942597
3   -3.164213
4    0.267006
Name: W, dtype: float64

In [10]:
type(df['W'])

pandas.core.series.Series

In [11]:
df[['W','Z']]

          W         Z
0 -1.128595  0.851138
1 -1.702400 -1.306226
2 -0.942597  1.176526
3 -3.164213  0.638019
4  0.267006 -1.257159

In [13]:
type(df[['W','Z']])

pandas.core.frame.DataFrame

In [14]:
df['new'] = df['W'] + df['Z']

In [15]:
df

          W         X         Y         Z       new
0 -1.128595 -1.737227 -0.242487  0.851138 -0.277457
1 -1.702400 -0.149407 -2.226871 -1.306226 -3.008626
2 -0.942597  1.718965 -1.069582  1.176526  0.233929
3 -3.164213 -0.153966 -0.322251  0.638019 -2.526194
4  0.267006  0.528366 -0.845436 -1.257159 -0.990153

In [16]:
df['raj'] = [1,2,3,4,5]

In [17]:
df

          W         X         Y         Z       new  raj
0 -1.128595 -1.737227 -0.242487  0.851138 -0.277457    1
1 -1.702400 -0.149407 -2.226871 -1.306226 -3.008626    2
2 -0.942597  1.718965 -1.069582  1.176526  0.233929    3
3 -3.164213 -0.153966 -0.322251  0.638019 -2.526194    4
4  0.267006  0.528366 -0.845436 -1.257159 -0.990153    5

In [18]:
df.drop('raj',axis=1)   # for columns axis = 0 for rows

          W         X         Y         Z       new
0 -1.128595 -1.737227 -0.242487  0.851138 -0.277457
1 -1.702400 -0.149407 -2.226871 -1.306226 -3.008626
2 -0.942597  1.718965 -1.069582  1.176526  0.233929
3 -3.164213 -0.153966 -0.322251  0.638019 -2.526194
4  0.267006  0.528366 -0.845436 -1.257159 -0.990153

In [19]:
df

          W         X         Y         Z       new  raj
0 -1.128595 -1.737227 -0.242487  0.851138 -0.277457    1
1 -1.702400 -0.149407 -2.226871 -1.306226 -3.008626    2
2 -0.942597  1.718965 -1.069582  1.176526  0.233929    3
3 -3.164213 -0.153966 -0.322251  0.638019 -2.526194    4
4  0.267006  0.528366 -0.845436 -1.257159 -0.990153    5

In [21]:
df.drop('raj',axis=1,inplace=True)

In [22]:
df

          W         X         Y         Z       new
0 -1.128595 -1.737227 -0.242487  0.851138 -0.277457
1 -1.702400 -0.149407 -2.226871 -1.306226 -3.008626
2 -0.942597  1.718965 -1.069582  1.176526  0.233929
3 -3.164213 -0.153966 -0.322251  0.638019 -2.526194
4  0.267006  0.528366 -0.845436 -1.257159 -0.990153

In [23]:
df

          W         X         Y         Z       new
0 -1.128595 -1.737227 -0.242487  0.851138 -0.277457
1 -1.702400 -0.149407 -2.226871 -1.306226 -3.008626
2 -0.942597  1.718965 -1.069582  1.176526  0.233929
3 -3.164213 -0.153966 -0.322251  0.638019 -2.526194
4  0.267006  0.528366 -0.845436 -1.257159 -0.990153

In [24]:
df.drop('new',axis=1,inplace=True)

In [25]:
df

          W         X         Y         Z
0 -1.128595 -1.737227 -0.242487  0.851138
1 -1.702400 -0.149407 -2.226871 -1.306226
2 -0.942597  1.718965 -1.069582  1.176526
3 -3.164213 -0.153966 -0.322251  0.638019
4  0.267006  0.528366 -0.845436 -1.257159

In [26]:
df.drop(3,axis=0)

          W         X         Y         Z
0 -1.128595 -1.737227 -0.242487  0.851138
1 -1.702400 -0.149407 -2.226871 -1.306226
2 -0.942597  1.718965 -1.069582  1.176526
4  0.267006  0.528366 -0.845436 -1.257159

In [27]:
df.drop(3,axis=0,inplace=True)

In [28]:
df

          W         X         Y         Z
0 -1.128595 -1.737227 -0.242487  0.851138
1 -1.702400 -0.149407 -2.226871 -1.306226
2 -0.942597  1.718965 -1.069582  1.176526
4  0.267006  0.528366 -0.845436 -1.257159

In [29]:
df.shape

(4, 4)

In [30]:
df.iloc[2]   # for accessing rows

W   -0.942597
X    1.718965
Y   -1.069582
Z    1.176526
Name: 2, dtype: float64

In [31]:
df.iloc[3]

W    0.267006
X    0.528366
Y   -0.845436
Z   -1.257159
Name: 4, dtype: float64

In [33]:
df = pd.DataFrame(np.random.randn(5,4),columns=['W','X','Y','Z'])

In [34]:
df

          W         X         Y         Z
0  0.223950  0.337135 -0.883820 -0.276216
1 -0.824398 -2.441078  3.954110 -0.925281
2  1.314355  0.956074  1.746942 -1.024657
3  0.198138  1.402927 -1.174590 -0.317324
4 -2.055257 -0.341586  0.627662  0.071738

In [35]:
df.iloc[0:,2:]

          Y         Z
0 -0.883820 -0.276216
1  3.954110 -0.925281
2  1.746942 -1.024657
3 -1.174590 -0.317324
4  0.627662  0.071738

In [36]:
df.iloc[2:,2:]

          Y         Z
2  1.746942 -1.024657
3 -1.174590 -0.317324
4  0.627662  0.071738

In [37]:
df.iloc[0:3,1:]

          X         Y         Z
0  0.337135 -0.883820 -0.276216
1 -2.441078  3.954110 -0.925281
2  0.956074  1.746942 -1.024657